name: Branch Merged Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  on_merge:
    name: On Merge to Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify pull request target branch
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" = "main" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            echo "Pull request merged into main branch."
          else
            echo "Pull request not merged into main branch. Skipping workflow execution."
            exit 1
          fi
          
      # Add your desired steps here
      # For example, you can run tests, build, or deploy after the branch is merged
      # Replace the following echo command with your actual build/test/deploy commands
      - name: Run tests or build or deploy
        run: echo "Running tests or build or deploy after branch merge."

