name: Deployment
concurrency:
  group: production
  cancel-in-progress: true
run-name: Deployment - ${{ github.actor }}
on: 
  push:
    branches:
      - 'release/*'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - run: echo ${{secrets.DO_GITHUB_PRIVATE_KEY}}