name: Deployment
concurrency:
  group: production
  cancel-in-progress: true
run-name: Deployment - ${{ github.actor }}
on: 
  push:
    branches:
      - 'release/*'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          sudo chmod 600  ~/.ssh/id_ed25519
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      - name: scp test
        run: |
          echo 'workspace ${{ github.workspace }}'
          echo $PWD
          touch zz.txt
          scp ./zz.txt tid@34.80.129.4:~/zz.txt