name: Unit-test
run-name: Unit-test - ${{ github.actor }}
on: 
  push:
    branches:
      - 'feature/*'
concurrency: 
  group: development
  cancel-in-progress: true
jobs:
  test-code:
    runs-on: ubuntu-22.04
    environment: development 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
      - name: Update-yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
      - name: Yarn install 
        run: yarn install --immutable
      - name: Start Test
        run: | 
          yarn test
          yarn test:e2e
