name: unit-test
run-name: unit-test - ${{ github.actor }}
on: 
  push:
    branches:
      - 'feature/*'
concurrency: 
  group: development
  cancel-in-progress: true
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    environment: production 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Restore node_modules
        id: cache-restore-node-modules
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: 'false'
          path: node_modules
          key: ${{ runner.os }}-rc-box-iot-server--
      - run: yarn
      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-rc-box-iot-server--${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-rc-box-iot-server--
      - run: yarn
      - run: yarn test
      - run: yarn test:e2e