name: Unit-test
run-name: Unit-test - ${{ github.actor }}
on: 
  pull_request:
    branches:
      - 'release/*'
concurrency: 
  group: development
  cancel-in-progress: true
jobs:
  test-code:
    runs-on: ubuntu-22.04
    environment: development 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
      - name: Update-yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn set version 3.6.1
      - name: Restore yarn
        id: cache-restore-node-yarn
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: 'false'
          path: ~/.yarn
          key: ${{ runner.os }}-iot-server-yarn--
      - name: Yarn install 
        run: yarn install --immutable
      - name: Store yarn
        uses: actions/cache@v3
        id: cache-node-yarn
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-iot-server-yarn--${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-iot-server-yarn--
      - name: Change Test DB HOST
        run: echo DB_HOST='${{ secrets.DBIP }}' >> .development.env
      - name: Start Test
        run: | 
          yarn test
          yarn test:e2e
