name: Unit-test
run-name: Unit-test - ${{ github.actor }}
on: 
  pull_request:
    branches:
      - 'release/*'
concurrency: 
  group: development
  cancel-in-progress: false
jobs:
  test-code:
    runs-on: ubuntu-20.04
    environment: development
    services:
      redis:
        image: redis
        ports:
        - 6379/tcp
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn
      - name: Update-yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn set version 3.6.4
      - name: Restore yarn
        id: cache-restore-node-yarn
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: 'false'
          path: ~/.yarn
          key: ${{ runner.os }}-iot-server-yarn--
      - name: Yarn install 
        run: yarn install --immutable
      - name: Store yarn
        uses: actions/cache@v3
        id: cache-node-yarn
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-iot-server-yarn--${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-iot-server-yarn--
      - name: Change Test DB HOST
        run: echo DB_HOST='${{ secrets.DBIP }}' >> .development.env
      - name: Change Test DB Password
        run: |
          sed -i 's/localDBPassword/${{ secrets.DB_PASSWORD }}/g' src/config/db.config.ts
      - name: Change Redis Port
        run: sed -i 's/6379/${{ job.services.redis.ports[6379] }}/g' src/config/redis.config.ts
      - name: Start Test
        run: | 
          yarn test
          yarn test:e2e
